name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Настраиваем SSH-агент и передаём passphrase
      - name: Setup SSH key with passphrase
        runs-on: ubuntu-latest
        # Установка expect
        run: |
          sudo apt-get update -qq && sudo apt-get install -qq -y expect

          # Запускаем агент и сохраняем его переменные окружения
          eval "$(ssh-agent -s)"

          # Сохраняем ключ в файл
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

          # Добавляем ключ через expect, автоматически отвечая passphrase
          expect << 'EOF'
            spawn ssh-add key.pem
            expect "Enter passphrase"
            send "${SSH_PASSPHRASE}\r"
            expect eof
      EOF
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      # 2. Копируем проект на сервер
      - name: Rsync to remote
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          rsync -avz --delete -e "ssh -p ${SSH_PORT:-22}" \
            ./* $SSH_USER@$SSH_HOST:/var/www/www-root/python-opc-api/

      # 3. На сервере ставим зависимости и запускаем скрипт
      - name: Install deps & run service
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -p ${SSH_PORT:-22} $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            cd /var/www/www-root/python-opc-api

            # создаём или активируем venv
            python3 -m venv venv || true
            source venv/bin/activate

            # ставим зависимости
            pip install --upgrade pip
            pip install -r requirements.txt

            # запускаем скрипт в фоне
            nohup python3 run_services.py > run_services.log 2>&1 &
          EOF