name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Настраиваем SSH-агент и передаём passphrase
      - name: Setup SSH key with passphrase
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE:  ${{ secrets.SSH_PASSWORD }}
          SSH_AUTH_SOCK:   /tmp/ssh_auth.sock
        run: |
          # запускаем агент
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null

          # сохраняем ключ во временный файл
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # скрипт-askpass для автоматической подачи фразы
          cat > askpass.sh << 'EOP'
          #!/bin/sh
          echo "$SSH_PASSPHRASE"
          EOP
          chmod +x askpass.sh

          # добавляем ключ в агент
          DISPLAY=none SSH_ASKPASS=$PWD/askpass.sh ssh-add key.pem

      # 2. Копируем проект на сервер
      - name: Rsync to remote
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          rsync -avz --delete -e "ssh -p ${SSH_PORT:-22}" \
            ./* $SSH_USER@$SSH_HOST:/var/www/www-root/python-opc-api/

      # 3. На сервере ставим зависимости и запускаем скрипт
      - name: Install deps & run service
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          ssh -p ${SSH_PORT:-22} $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            cd /var/www/www-root/python-opc-api

            # создаём или активируем venv
            python3 -m venv venv || true
            source venv/bin/activate

            # ставим зависимости
            pip install --upgrade pip
            pip install -r requirements.txt

            # запускаем скрипт в фоне
            nohup python3 run_services.py > run_services.log 2>&1 &
          EOF